<?php
/**
 * @var \Smartosc\Article\Block\Detail $block
 */

//print_r( $block->collection() );
?>

<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 30px;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    .article-id {
        width: 5%
    }

    .article-title {
        width: 20%
    }
    .article-content {
        width: 30%
    }
    .article-image {
        width: 25%
    }
    .article-create {
        width: 10%
    }.article-update {
         width: 10%
     }

</style>
<body>
<table>
    <tr>
        <th class="article-id">Id</th>
        <th class="article-title">Title</th>
        <th class="article-content">Content</th>
        <th class="article-image">Image</th>
        <th class="article-create">Create At</th>
        <th class="article-update">Update At</th>
    </tr>
    <?php
    foreach ($block->getArticleCollection() as $article) { ?>
        <tr>
            <td><?= $article['article_id'] ?></td>
            <td><?= $article['title'] ?></td>
            <td><?= $article['content'] ?></td>
            <td><?= $article['image'] ?></td>
            <td><?= $article['created_at'] ?></td>
            <td><?= $article['updated_at'] ?></td>
        </tr>
    <?php } ?>
</table>
</body>
</html>